name: nextron-python-sample
channels:
  - fastai
  - peterjc123
  - pytorch
  - defaults
dependencies:
  - certifi
  - cffi
  - click
  - flask
  - future
  - gevent
  - greenlet
  - itsdangerous
  - jinja2
  - markupsafe
  - msgpack-python
  - pip
  - pycparser=2.19
  - python
  - setuptools
  - werkzeug
  - wheel=0.32.2
  - pip:
      - flask-cors
      - flask-graphql
      - graphene
      - pyinstaller
